name: auto_const
description: A CLI that adds const keyword on anywhere possible.
version: 1.0.2
homepage: https://github.com/carlosfiori/dart-auto-const
repository: https://github.com/carlosfiori/dart-auto-const
issue_tracker: https://github.com/carlosfiori/dart-auto-const/issues

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.1

executables:
  dart-auto-const: auto_const
